export const documentRequired = [
    { label: "SLC (Original)", name: "slc" },
    { label: "Birth Certificate", name: "birthCertificate" },
    { label: "Result of Last class", name: "lastClassResult" },
    { label: "Student Blood Group", name: "studentBloodGroupDoc" },
    { label: "Student & family SSSM ID", name: "studentFamilySssmId" },
    { label: "CBSE registration of class 9th", name: "cbseRegClass9" },
    { label: "Aadhar card of Student, Father, Mother & Guardian (if any)", name: "aadhaarAll" },
    { label: "Shapath patra for class 8th onwards", name: "shaphatPatraClass8" },
    { label: "5 passport size photographs of student and 1 photograph of Father & Mother", name: "passportPhotos" },
];

export const stScObcDocs = [
    { label: "Students Digital caste certificate", name: "studentDigitalCasteCert" },
    { label: "Parents income certificate", name: "parentsIncomeCert" },
    { label: "Student Bank account passbook", name: "studentBankPassbook" },
    { label: "Father's caste certificate (only for class 1st & KG)", name: "fatherCasteCert" },
];

export const initialValues = {
    formNo: "",
    penNo: "",
    scholarNo: "",
    admissionDate: "",
    firstName: "",
    middleName: "",
    lastName: "",
    firstNameHindi: "",
    middleNameHindi: "",
    lastNameHindi: "",
    DOB: "",
    dobWords: "",
    gender: "",
    religion: "",
    caste: "",
    subCaste: "",
    email: "",
    perAddress: "",
    currentAddress: "",
    aadhaar: "",
    bloodGroup: "",
    stuBankAccNo: "",
    ifsc: "",
    ssin: "",
    familySsn: "",
    fatherName: "",
    motherName: "",
    guardianName: "",
    fatherQual: "",
    motherQual: "",
    guardianQual: "",
    fatherOcc: "",
    motherOcc: "",
    guardianOcc: "",
    fatherDesignation: "",
    motherDesignation: "",
    guardianDesignation: "",
    fatherDepartment: "",
    motherDepartment: "",
    guardianDepartment: "",
    fatherAnnualIncome: "",
    motherAnnualIncome: "",
    guardianAnnualIncome: "",
    fatherMobile: "",
    motherMobile: "",
    guardianMobile: "",
    prevSchoolName: "",
    palce: "",
    lastClass: "",
    result: "",
    session: "",
    cbseRegNo: "",
    hostelName: "",
    contactNumber: "",
    nameOfBrotherORSister: "",
    classOfBrotherORSister: "",
    studyingINSISAOfBrotherorSister: "",
    studyingINSISAOfBrotherorSisterClass: "",
    parentDOB: "",
    parentSign: null,
    parentName: "",
    relation: "",
    signOfAccAuthority: null,
    signOfScholAuthority: null,
    stuName: "",
    class: "",
    studentPhoto: null,
    fatherPhoto: null,
    motherPhoto: null,
    guardianPhoto: null,
    formIssueDate: "",
    authorizedSign: null,

    // Document Required
    slc: null,
    birthCertificate: null,
    lastClassResult: null,
    studentBloodGroupDoc: null,
    studentFamilySssmId: null,
    cbseRegClass9: null,
    aadhaarAll: null,
    shaphatPatraClass8: null,
    passportPhotos: null,

    // ST/SC/OBC Docs
    studentDigitalCasteCert: null,
    parentsIncomeCert: null,
    studentBankPassbook: null,
    fatherCasteCert: null,
};
